### ISSUE TITLE
Platform error sensor.openweathermaphistory - Exception importing custom_components.openweathermaphistory.sensor

### ISSUE THREAD

**Issue by dirkg173** [briis/hass-weatherflow#48]
Hi,

since a few days the following error message is displayed when I want to restart HA (Developer Tools -> YAML -> Restart):
_The system cannot restart because the configuration is not valid: Platform error sensor.openweathermaphistory - Exception importing custom_components.openweathermaphistory.sensor_
Furthermore, the following error messages are displayed in the HA log:

_Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:707
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:50:43 (1 occurrences)
Last logged: 10:50:43

[547577543456] The system cannot restart because the configuration is not valid: Platform error sensor.openweathermaphistory - Exception importing custom_components.openweathermaphistory.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 707, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.openweathermaphistory - Exception importing custom_components.openweathermaphistory.sensor_

---

_Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:696
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:50:43 (1 occurrences)
Last logged: 10:50:43

The system cannot restart because the configuration is not valid: Platform error sensor.openweathermaphistory - Exception importing custom_components.openweathermaphistory.sensor_

---

_Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/openweathermaphistory/sensor.py:55
Integration: openweathermaphistory (documentation, issues)
First occurred: 09:58:03 (2 occurrences)
Last logged: 10:50:43

Unexpected exception importing platform custom_components.openweathermaphistory.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/openweathermaphistory/sensor.py", line 55, in <module>
    vol.Optional(CONF_UNIT_SYSTEM, default=CONF_UNIT_SYSTEM_METRIC): cv.unit_system,
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'unit_system'_

---

Unfortunately, I can not remember when the problem started.

Current configuration:
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest
WeatherFlow integration v1.0.8

I am quite inexperienced with HA, should you need any further information, please let me know.

BR
Dirk

**Comment by briis** [comment]
Hi Dirk,
Sorry you have this issue, but it is not related to the WeatherFlow integration. If you look at the logfile you will find lines like this `/config/custom_components/openweathermaphistory/sensor.py"` so your errors are related to an integration called `openweathermaphistory`. Please post your error there.

**Comment by dirkg173** [comment]
Oh, sorry about that. I mixed up the error messages with Weatherflow.
Sorry for the unnecessary request.
