### ISSUE TITLE
Error setting weatherflow entries

### ISSUE THREAD

**Issue by pwm802** [briis/hass-weatherflow#78]
I have three instances of weatherflow integration that were running without issue.  I updated HA to:

Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

I now have the following errors in the log:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/weatherflow/__init__.py", line 72, in async_setup_entry
if hass.config.units.is_metric
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UnitSystem' object has no attribute 'is_metric'
2023-08-22 09:01:35.266 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ####### for weatherflow

**Comment by briis** [comment]
This is an old issue which has bee fixed. Please upgrade to the latest version.
