### ISSUE TITLE
Weatherflow integration gone and can't reinstall

### ISSUE THREAD

**Issue by jrossey** [briis/hass-weatherflow#79]
I previously installed the weatherflow integration through HACS and it was working flawlessly for a long time. Since last week the sensors are Unavailble and the integration seems to have dissapeared: it is no longer shown in the Settings/Integrations and it is also not shown in the HACS menu. 
I can add the Weatherflow repository again in the HACS menu but when I do that I get a "Unknown error" message with no other info.

The Tempest device is still shown under the MQTT integration, but all the sensors are Unavailable.

I had some issues last week with MQTT where I disabled the MQTT integration and re-enabled it. I also had to revert back to a back-up after upgrading HA to the latest version. Can this have caused it?

I see this error in the logs of WEATHERFLOW TO MQTT:
`INFO:weatherflow2mqtt.weatherflow_mqtt:🏠 Home Assistant Supervisor Mode 🏠
ERROR:weatherflow2mqtt.weatherflow_mqtt:Could not read Home Assistant core config: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://supervisor/core/api/config')
INFO:weatherflow2mqtt.weatherflow_mqtt:Timezone is Europe/Brussels
INFO:weatherflow2mqtt.weatherflow_mqtt:Unit System is metric
INFO:weatherflow2mqtt.weatherflow_mqtt:Zambretti Values: 960.0 and 1060.0
INFO:weatherflow2mqtt.weatherflow_mqtt:Connected to the MQTT server at 192.168.0.218:1883
INFO:weatherflow2mqtt.weatherflow_mqtt:The UDP server is listening on port 50222
INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Hub sensor: Status
INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Status
...
`

This is an error from the Supervisor logs, not sure if it is related:
`23-08-28 11:05:05 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-266054' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreJobError("'GitRepo.pull' blocked from execution, no supervisor internet connection")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 116, in wrapper
    raise self.on_condition(error_msg, _LOGGER.warning) from None
supervisor.exceptions.StoreJobError: 'GitRepo.pull' blocked from execution, no supervisor internet connection`

Any idea on how I can fix this?

**Comment by jrossey** [comment]
Ok I feel really embarassed now. I did find the Weatherflow-to-mqtt. It is not under HACS or Integrations, it is under Add-Ons. 

It is working again. Not sure what I did to get it working, I enabled the Watchdog and Auto Update option for the Add-on. I also enabled Auto Discovery in the MQTT Integration configuration.
