### ISSUE TITLE
Version 1.0.16 Breaking

### ISSUE THREAD

**Issue by thoward1234** [briis/hass-weatherflow#84]
I had the documented issue with version 1.0.14 and upgraded to 1.0.16.  After install (using HACS) I still cannot get the integration to load.  Below is the error from the log:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/weatherflow/__init__.py:82
Integration: WeatherFlow Weather (documentation, issues)
First occurred: 9:49:15 AM (2 occurrences)
Last logged: 9:49:32 AM

Error setting up entry Home Station for weatherflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherflow/__init__.py", line 82, in async_setup_entry
    weatherflowapi = WeatherFlowApiClient(
                     ^^^^^^^^^^^^^^^^^^^^^
TypeError: WeatherFlowApiClient.__init__() got an unexpected keyword argument 'ignore_fetch_errors'

**Comment by PYehl73** [comment]
I have completely uninstalled it from HACS, deleted the files in data studio, rebooted, reinstalled it, restarted - and I'm still not getting all my data...  only loading 45 entities:

<img width="319" alt="image" src="https://github.com/briis/hass-weatherflow/assets/119134827/9557a53f-60d3-4890-bc07-4c9eebf0b05d">


<img width="404" alt="image" src="https://github.com/briis/hass-weatherflow/assets/119134827/09e2e14e-e8f1-43e9-b0f0-e1792fede25c">

**Comment by JohnHof1275** [comment]
mine also not working 
![Screenshot 2023-09-07 221429](https://github.com/briis/hass-weatherflow/assets/87447868/ef0b0f0c-f6d1-4147-9c8b-c29481aed14e)

**Comment by JtwoA** [comment]
@briis I think Weatherflow AND Home Assistant are making breaking changes lately.

**Comment by briis** [comment]
It is working fine here.

The error indicates that there are some old stuff around. Try and delete the integration from HA *Devices & services* and HACS. Then open a file browser and in your *config* directory go to *custom_components* and make sure that the *weatherflow* directory is completely deleted (If not, delete it).

Then restart HA. Install again from HACS, and restart again. The go to *Devices & services* again and install again, and see if that helps.

**Comment by JtwoA** [comment]
@briis This integration is working fine for me - the Weatherflow2MQTT you've written is having an issue wherein it doesn't stay running.  My comment above was on a more global level as both Weatherflow and HA have been making some changes.

**Comment by KCXLT** [comment]
I'm only getting 45 entities also.  I'm new to this and had the HACS integration and the MQTT installed with the Weather station under a different name.  I had all the entities.  Today I deleted the MQTT and uninstalled the HACS integration and rebooted.  Reinstalled the HACS integration and only have the 45 entities.  Missing a lot of the wind and Feel Like to name a few.

**Comment by briis** [comment]
> global level as both Weatherflow and HA have been making some changes.

With the exception of the new Forecast structure introduced in 2023.9 all changes should have been implemented. 
I am working on a new separate Forecast Integration, as it seems someone is creating a Core WeatherFlow integration, using the same Domain name as this integration, but without the forecast piece, as he is using the UDP API to get the data. At the point of that arriving, I will discontinue this Integration.

> I'm only getting 45 entities also

The WeatherFlow2MQTT integration has more calculated sensors than this integration, so there will be a difference.

**Comment by KCXLT** [comment]
Ok. Thanks for answering that for me.

Kevin
________________________________

**Comment by longunmin** [comment]
I am having a similar issue. I am getting all sensor entities except for the `weather.` entity.  Here is my warning

Logger: homeassistant.setup
Source: setup.py:340
First occurred: 2:14:18 PM (1 occurrences)
Last logged: 2:14:18 PM

Unable to prepare setup for platform weatherflow.weather: Platform not found (cannot import name 'ATTR_FORECAST_HUMIDITY' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)).

**Comment by KCXLT** [comment]
Just an update.  Yesterday I re-installed the Integration 3 times I think, and only got 45 entities.  On the 3rd try and the Integration wouldn't even connect, just the keep trying message.  I just needed a break at that point so walked away.  About a minute later I got a notification that my station was off-line.  We haven't had much sun here for a while and the battery had run out.

This morning we had sun and after a bit the Integration connected.  Later this afternoon I checked and I now have 58 entities.  Just guessing, I know the Tempest goes into battery saving mode when the battery gets low and slows or stops reporting some values.  Maybe this is the problem others are having.

**Comment by JtwoA** [comment]
> battery level isn't the issue mine is having. Still only 45 entities showing. I'll try to delete everything yet again and reinstall. What a pain this integration has become.

Someone took the time to write, for free, a plugin between two services that they do not own, manage, or otherwise control.  One or both of those services has made a change - but you rant at the person who made you a free thing?

You should probably uninstall this plugin - it's not for you.

**Comment by scstraus** [comment]
I am also missing all of the wind entities. Everything else seems to work.
